version: 0.2
env:
  parameter-store:
     DOCKER_REGISTRY_USERNAME: docker-username
     DOCKER_REGISTRY_PASSWORD: docker-password
    
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn test
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - echo building the docker image
    - docker build -t dsmouli/mavenwebapp:44 .
    - echo login into docker
    - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD"
    - echo push the docker image
    - docker push dsmouli/mavenwebapp:44
artifacts:
  files:
  - target/maven-web-application.war
